### ISSUE TITLE
Ceph cluster reporting HEALTH_WARN

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#11]
This is making prometheus and alert manager blow up my phone, everything appears to be working fine even though cephs status is `HEALTH_WARN`.

Currently this is returning true `ceph_health_status{job="rook-ceph-mgr"} == 1`

**Comment by onedr0p** [comment]
Fixed by going into the ceph tool box and archiving the crash report, see below docs

https://github.com/onedr0p/k3s-gitops/blob/master/docs/rook-ceph.md

Now ceph is reporting a `HEALTH_OK` status

**Comment by billimek** [comment]
I had this same problem, thank you for sharing the 'fix'!
