### ISSUE TITLE
Swap Docker CRI with containerd

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#13]
Using Docker isn't really needed, or is it? A couple concerns are:

- Internal DNS, I use a separate device running PiHole for this, does containerd allow setting a DNS like Docker?
- Building container images if I ever start using DroneCI maybe with https://github.com/GoogleContainerTools/kaniko

**Comment by onedr0p** [comment]
I did this for my two worker nodes, one at a time:

```
kubectl drain <node>
kubectl delete node <node>
```

Now I am unsure if doing this on my master and storage nodes will have a negative impact.

**Comment by carpenike** [comment]
Doing your master would probably brick ya wouldn't it?

Storage (Ceph) should be able to do one at a time... treat it like a ceph OSD failure and flatten the node entirely / bring it back in.

**Comment by carpenike** [comment]
... but take a backup first. :-D

**Comment by onedr0p** [comment]
Yea, master is the hard one :)
I will probably wait until I can get my app data properly backed up and a way to restored before I do the rest. I can tear is all down and stand it back up.

**Comment by onedr0p** [comment]
Implementing this on my iteration of my cluster

**Comment by onedr0p** [comment]
Done
