### ISSUE TITLE
Prometheus Operator complains about: skipping unknown hook: "crd-install"

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#19]
Related issue: https://github.com/helm/charts/issues/17511

https://github.com/helm/charts/issues/19452

**Comment by onedr0p** [comment]
Testing out this change:

Moreover in the docs for `prometheusOperator.createCustomResource=false`

> Regardless of value of this, Helm v3+ will install the CRDs if those are not present already. Use --skip-crds with helm install if you want to skip CRD creation.

My understanding of that is if you are using helm 3 make sure you have `prometheusOperator.createCustomResource=false` so that the warnings don't show up.

**Comment by onedr0p** [comment]
This worked, closing.

**Comment by rosscdh** [comment]
still exists with template

```
helm template my-release stable/prometheus-operator
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
```
