### ISSUE TITLE
Explore Backing up and restoring PVCs

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#26]
Figure out best way to backup and restore PVCs

- [Stash](https://github.com/stashed/stash)
- [Velero](https://github.com/vmware-tanzu/velero)

**Comment by carpenike** [comment]
We ruling out [Kasten](https://www.kasten.io/)?

**Comment by onedr0p** [comment]
I'm indifferent about it, seems like overkill and a lot to learn about their platform compared to the alternatives.

I feel like we need to raise our issues with stash and velero to their repos and hope they hear us.

**Comment by carpenike** [comment]
I would agree. I also wonder how many of our "issues" will go away once Stash GA's. Currently still in RC.

**Comment by onedr0p** [comment]
I should have recorded my errors and issues and open an issue on their GH. oh well, I'll try again when a new RC drops.

**Comment by onedr0p** [comment]
Related https://github.com/onedr0p/k3s-gitops/issues/49

**Comment by onedr0p** [comment]
https://github.com/billimek/k8s-gitops/issues/146#issuecomment-656338785
