### ISSUE TITLE
Look into a status page for services

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#27]
This will hosted on a $5/month droplet or somewhere else outside my home network and monitor the services I host. Couple options to consider

- https://cachethq.io/
- https://statusfy.co/

**Comment by carpenike** [comment]
I love this idea.

**Comment by onedr0p** [comment]
I went with uptimerobot.com, they actually have a good catalog of features for $8/month.

Things like 2FA, RSS, API access, HTTP, Ping, Heartbeat based monitoring, and a custom status page which shows the status of your services. The custom status page can be added to a CNAME to your domain so you can get a `status.myawesomewebsite.com`
