### ISSUE TITLE
K3s vs rke/K8s

### ISSUE THREAD

**Issue by carpenike** [onedr0p/k3s-gitops#4]
What made you choose k3s over rke/k8s? I think you’re all x86, right?

**Comment by onedr0p** [comment]
I started out with RPis and guess I just stuck with k3s because it was so easy to set up. I am all x86 now though.

I know there's a bunch of chat apps out there but if you already have Discord you can find me if you wanted to chat more. I am also on the homelab discord group.

onedr0p#6357
