### ISSUE TITLE
Monitor kube controller and scheduler

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#46]
Currently an issue with k3s?

https://github.com/rancher/k3s/issues/425

**Comment by onedr0p** [comment]
Done with adding 

https://github.com/onedr0p/k3s-gitops/tree/master/deployments/monitoring/kube-controller

and 

https://github.com/onedr0p/k3s-gitops/tree/master/deployments/monitoring/kube-scheduler

**Comment by dharmendrakariya** [comment]
page is broken i guess, can you provide solution

**Comment by onedr0p** [comment]
I do not get these metrics anymore because they would stop reporting intermittently and my alert manager would blow up.
