### ISSUE TITLE
Replace MetalLB with Calico BGP peering

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#67]
I couldn't say it any better then @bjw-s

https://github.com/bjw-s/k8s-gitops/issues/3

**Comment by carpenike** [comment]
oneofus, oneofus

**Comment by bjw-s** [comment]
All done... Join us on the dark side, we have cookies!

**Comment by onedr0p** [comment]
Step one in getting BGP working with metallb is done. Next step installing calico!

**Comment by carpenike** [comment]
@bjw-s got the good cookies where he's from. I'd take him up on the offer.

**Comment by onedr0p** [comment]
I demand cookies, this is all done.

Thanks for you help guys!

**Comment by kifeo** [comment]
Thanks, do you have also egress traffic source natted (not using the node IP ?)

**Comment by onedr0p** [comment]
Hi @kifeo I have my router pointing to a my [nginx-ingress externalIP](https://github.com/onedr0p/k3s-gitops/blob/master/deployments/networking/nginx-ingress-external.yaml#L26) on port 80 and 443

Does that answer your question?

**Comment by kifeo** [comment]
Thanks @onedr0p 
I think what I was looking for is https://docs.projectcalico.org/networking/workloads-outside-cluster
I will try it in the next days

**Comment by onedr0p** [comment]
@kifeo can you explain a bit more what that does? I am not following the documentation lol

**Comment by kifeo** [comment]
@onedr0p Sorry for the late reply, I reverted to MetalLB as Calico was peered but not advertising the ExternalIPs, so I did not check the implementation of IPPools, which is maybe was I was looking for.
