### ISSUE TITLE
[Question] Difference between generate-helm-secret.sh and generate-sealed-secrets.sh

### ISSUE THREAD

**Issue by blmhemu** [onedr0p/k3s-gitops#74]
What is the between generate-helm-secret.sh and generate-sealed-secrets.sh ?
Is it just that generate-sealed-secrets.sh loops over all .txt while generate-helm-secret.sh takes just a single file ?

**Comment by onedr0p** [comment]
You got it right. My plan was to use the `generate-helm-secret.sh` over `generate-sealed-secrets.sh` but I haven't had time to go back to this.

**Comment by blmhemu** [comment]
But why would u want to use `generate-helm-secret.sh` instead of `generate-sealed-secrets.sh` ? Would it not be cumbersome to input each and every file ?

**Comment by onedr0p** [comment]
I was thinking to use this in an automated fashion with GitHub actions like I currently do now. But instead move the loop logic into my GitHub action and call this script. Each way has its positives or negatives. I'm trying to find a sweet spot that will work well for automation and manually running it.

**Comment by blmhemu** [comment]
Ok got it Thanks for the info. Closing the issue.
